/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/ServiceCard/card.vue')['default']
    CardWithoutImage: typeof import('./src/components/ServiceCardWithoutImage/CardWithoutImage.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HomeCard: typeof import('./src/components/HomeCard/HomeCard.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCard: typeof import('./src/components/ServiceCard/ServiceCard.vue')['default']
    ServiceCardWithoutImage: typeof import('./src/components/ServiceCardWithoutImage/ServiceCardWithoutImage.vue')['default']
    SteffCrad: typeof import('./src/components/SteffCard/steffCrad.vue')['default']
  }
}
