/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('./src/components/ServiceCard/card.vue')['default']
    CardWithoutImage: typeof import('./src/components/ServiceCardWithoutImage/CardWithoutImage.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HeaderPages: typeof import('./src/components/HeaderPages/HeaderPages.vue')['default']
    HomeCard: typeof import('./src/components/HomeCard/HomeCard.vue')['default']
    InlineMessage: typeof import('primevue/inlinemessage')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    InputText: typeof import('primevue/inputtext')['default']
    NavigationBar: typeof import('./src/components/NavigationBar/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCard: typeof import('./src/components/ServiceCard/ServiceCard.vue')['default']
    ServiceCardWithoutImage: typeof import('./src/components/ServiceCardWithoutImage/ServiceCardWithoutImage.vue')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
    StaffCard: typeof import('./src/components/StaffCard/staffCard.vue')['default']
  }
}
