/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('./src/components/ServiceCard/card.vue')['default']
    CardWithoutImage: typeof import('./src/components/ServiceCardWithoutImage/CardWithoutImage.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HeaderPages: typeof import('./src/components/HeaderPages/HeaderPages.vue')['default']
    HomeCard: typeof import('./src/components/HomeCard/HomeCard.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    InputText: typeof import('primevue/inputtext')['default']
    NavigationBar: typeof import('./src/components/NavigationBar/NavigationBar.vue')['default']
    NotificationCard: typeof import('./src/components/NotificationCard/NotificationCard.vue')['default']
    OrderCard: typeof import('./src/components/OrderCard/OrderCard.vue')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    StaffCard: typeof import('./src/components/StaffCard/staffCard.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
  }
}
